### ISSUE TITLE
session_write_close(): Failed to write session data using user defined save handler.

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-session#6]
Occasionally,we get the following not yet reproducible warning:

> WARN: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) {"errno":2,"file":"/var/www/html/vendor/zendframework/zend-session/src/SessionManager.php","line":229}

This is how we initialize the session:

```php
// Load config
$config = $serviceManager->get('Config');

// Initialize session
$sessionConfig = new SessionConfig();
$sessionConfig->setOptions($config['session']);

$sessionTableGateway = new TableGateway('session', $serviceManager->get('Zend\Db\Adapter\Adapter'));
$saveHandler = new DbTableGateway($sessionTableGateway, new DbTableGatewayOptions());

$sessionManager = new SessionManager($sessionConfig, null, $saveHandler);
$sessionManager->setName($config['session']['name']);

$sessionManager->start();

Container::setDefaultManager($sessionManager);
```

---

Originally posted by @intellent at https://github.com/zendframework/zend-session/issues/77

**Comment by weierophinney** [comment]
I am facing a similar issue since upgrading to PHP 7.1 . I should note though, that we are using a VERY old version of Zend Framework: 1.10.

I do notice though that your session.save_path seems to be empty?
`(session.save_path: )`
There should probably be something there like /var/lib/php/session

---

Originally posted by @cg923 at https://github.com/zendframework/zend-session/issues/77#issuecomment-367077229

**Comment by weierophinney** [comment]
Yes, I am facing exactly the same issue here. I am using also the session-db, i don't know why he reproduces this error pointing to something like if was saved on local disk.

![captura de ecra 2018-09-11 as 11 54 04](https://user-images.githubusercontent.com/5594091/45355842-6dc4ee80-b5b9-11e8-8577-2ec82e0a6f8e.png)




---

Originally posted by @apoca at https://github.com/zendframework/zend-session/issues/77#issuecomment-420232689

**Comment by weierophinney** [comment]
I'm also experienced the same issue but my particularity is that the session save handler want well to store user id (after logging) but doesn't want to store data session cart to sessiondb

---

Originally posted by @jamelcity at https://github.com/zendframework/zend-session/issues/77#issuecomment-422478036

**Comment by weierophinney** [comment]
:thinking: I'm facing the exact same issue when I use `Zend\Cache\Storage\Adapter\BlackHole::class` as save handler

---

Originally posted by @Nguimjeu at https://github.com/zendframework/zend-session/issues/77#issuecomment-515392471

**Comment by weierophinney** [comment]
I also occasionally experience the error (`E_WARNING`):

    session_write_close(): Failed to write session data using user defined save handler. 
    (session.save_path: /var/lib/php/sessions)

in `src/SessionManager.php` on line 234.

What is interesting is that I am using `Zend\Session\SaveHandler\DbTableGateway` as a `SaveHandler`.

The session with the session ID included in the error log is not stored in the database.

The error happens sporadically and is not reproducible.

I am using `zend-session 2.9.1`.

---

Originally posted by @jonathanmaron at https://github.com/zendframework/zend-session/issues/77#issuecomment-565352489

**Comment by apoca** [comment]
Yes unfortunately we have the same error here..

**Comment by FabianKoestring** [comment]
I think we have the exact same problem. We use our own SaveHandler and getting this exception ....

`
2020/11/20 11:23:59 [error] 16683#16683: *34849755 FastCGI sent in stderr: "PHP message: Doctrine\ORM\Cache\CacheException: Cannot update a readonly entity "...\Filemanager\Entity\File" in /var/www/stack/src/www/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/CacheException.php:50
Stack trace:
#0 /var/www/stack/src/www/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/Persister/Entity/ReadOnlyCachedEntityPersister.php(39): Doctrine\ORM\Cache\CacheException::updateReadOnlyEntity()
#1 /var/www/stack/src/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1172): Doctrine\ORM\Cache\Persister\Entity\ReadOnlyCachedEntityPersister->update()
#2 /var/www/stack/src/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(407): Doctrine\ORM\UnitOfWork->executeUpdates()
#3 /var/www/stack/src/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(371): Doctrine\ORM\UnitOfWork->commit()
#4 /var/www/stack/src/vendor/.../service/src/Session.php(51): Doctrine\ORM\EntityManager->flush()
#5 /var/www/stack/src/www/module/Application/src/Session/SaveHandler/Doctrine.php(68): ...\Ser...PHP message: PHP Warning:  session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/sessions) in /var/www/stack/src/www/vendor/laminas/laminas-session/src/SessionManager.php on line 235" while reading upstream, client: 54.236.1.13, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm-www.sock:"
`

**Comment by StefanGerl** [comment]
Is this issue still occuring with laminas-session versions > 2.9.1?
Did anybody resolve this issue with an upgrade of the laminas-session Version?
I am still facing this problem, I am using laminas-session 2.8.7, with php7.3-fpm.

**Comment by tyrsson** [comment]
Im still getting the same random error with laminas-session 2.13.0, DbTableGateway SaveHandler, php 8.1.1, windows 10

**Comment by romantaranenko-hometogo** [comment]
@StefanGerl `laminas/laminas-session` version `2.12.1` with PHP `8.1.13` and i have it.

**Comment by Ocramius** [comment]
Errors like these seem unrelated:

 > Cannot update a readonly entity 

I'm closing here: please consider opening a new issue with logs presenting exactly:

 * which session savehandler was used
 * how it was configured
 * which method calls on the savehandler have been performed (you may need to decorate it)

**Comment by rsalbin** [comment]
Still facing the same issue as others:
session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) {"errno":2,"file":"/var/www/vendor/laminas/laminas-session/src/SessionManager.php","line":240}

It fires only when user is loggedin, can't find other details.
